### ISSUE TITLE
Issue: Emik is smart

### ISSUE THREAD

**Issue by UnrulyJuli3** [Emik03/KeepCoding#1]
Dumb pls

**Comment by Emik03** [comment]
The oldest version of `KeepCoding` exists as [`EmikBaseModules`](https://github.com/Emik03/Updog/tree/6f29f15435ebbadb9dec9ada3a7c6efb86936346/Assets/Scripts/EmikBaseModule). You should find dumb there.

**Comment by UnrulyJuli3** [comment]
Oh thank you very much
